# Change these first
owner: johndo100 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Phong Lan Tech
    url: https://phonglan.vn

status-website:
  baseUrl: /upptime
  name: John Do Status Website

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
